version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: my_postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
